ARG BASE_IMAGE=ubuntu:22.04
FROM ${BASE_IMAGE}

# Install ros-humble-rmw-zenoh-cpp
RUN apt-get update && apt-get install -y \
    ros-humble-rmw-zenoh-cpp && \
    rm -rf /var/lib/apt/lists/*

ENV RMW_IMPLEMENTATION=rmw_zenoh_cpp
ENV ZENOH_ROUTER_CONFIG_URI=/workspaces/config/DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5
